### ISSUE TITLE
1.6.3-1.6.4 Save corruption (WITH SAVES)

### ISSUE THREAD

**Issue by Marxon1134** [wmtorode/MW5-SaveEditor#35] opened 2024-02-12 23:04 UTC
1.6.4 is showing the issue more than 1.6.3 which I was able to get to sometimes work by deleting the config and redownloading the executable.
Issue being with 1.6.4 is that even opening and re saving a file with zero changes causes most elements to become unreadable such as mechs inventory date, basically everything excluding your current location.
Attached are two save files, one of the original save and one that was merely read then resaved by 1.6.4 editor, hope this helps diagnose whats being done.
For me the original and the 1.6.3 resaved ones load but the 1.6.4 does not.
[saves.zip](https://github.com/wmtorode/MW5-SaveEditor/files/14251815/saves.zip)

**Comment by Kstims** [comment] 2024-02-14 21:16
I used 1.6.3 because 1.6.4 would erase all my YAML stuff. I'd load the save in 1.6.4, edit something small like add 10 extra c-bills. save, then load that into the game. It would treat my save like it was a new installation of YAML, and my mechlab and equipment would be completely empty.

Anyway, I was able to use 1.6.3 for a while, however eventually something happened to my save where none of my friends were able to load into the game and were stuck on the load screen or a black field with stars forever, a fresh new game with the same mods I was running and they were able to load in instantly. I dont know if that issue was caused by the save editor corrupting something or if the mods had an issue though.

**Comment by Marxon1134** [comment] 2024-02-14 21:20
In my experience 1.6.2 is a viable fallback option, it can't add items from new dlcs but it will not break the save.

**Comment by Kstims** [comment] 2024-02-14 21:22
> In my experience 1.6.2 is a viable fallback option, it can't add items from new dlcs but it will not break the save.

Were you completely unable to see the DLC items? When I used 1.6.3, I wasn't able to add any new items, like I couldn't add a clan ER M laser, but if I already had one in my inventory, it would appear in the dropdown list as well as the listing of my inventory.

**Comment by SerBrynden** [comment] 2024-02-15 01:48
Related to #34 and #36.

**Comment by Marxon1134** [comment] 2024-02-15 02:17
> Related to #34 and #36.

Understood, this issue was primarily to provide sample save files to assist with diagnosing the issue, mods were not used in my case.

**Comment by wmtorode** [comment] 2024-02-29 04:50
This should be fixed by 1.6.5

**Closed by wmtorode** 2024-02-29 04:50 UTC
